# Generated by Django 6.0.7 on 2026-07-22 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orderitem_unit_cost_price_product_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('attendant', 'Attendant'), ('cashier', 'Cashier'), ('dispatcher', 'Dispatcher')], max_length=20)),
                ('pin', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to='core.posuser'),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_orders', to='core.posuser'),
        ),
        migrations.AddField(
            model_name='order',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to='core.posuser'),
        ),
    ]
